apiVersion: apps/v1
kind: Deployment
metadata:
  # Unique key of the Deployment instance
  name: deployment-color-changer-app
spec:
  # 3 Pods should exist at all times.
  replicas: 3
  selector:
    matchLabels:
      app: color-changer
  template:
    metadata:
      labels:
        # Apply this label to pods and default
        # the Deployment label selector to this value
        app: color-changer
    spec:
      containers:
      - name: color-changer
        # Run this image
        image: vishalksemin/color-changer:1.2